services:
  mysqldb-source:
    image: mysql
    container_name: mysqldb-source
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql_data:/docker-entrypoint-initdb.d
  etl-pipeline:
    image: python:3.12-slim
    container_name: etl-pipeline
    restart: always
    volumes:
      - ./etl:/app
    working_dir: /app
    # command: python main.py
