services:
  mysqldb-source:
    image: mysql
    container_name: mysqldb-source
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - etl-networks

  # etl-pipeline:
  #   image: python:3.12-slim
  #   container_name: etl-pipeline
  #   depends_on:
  #     - mysqldb-source
  #   restart: always
  #   volumes:
  #     - ./script/etl:/app
  #   working_dir: /app
  #   networks:
  #     - etl-networks
  #   command: sh -c "while true; do sleep 3600; done"
    # python pipeline.py

networks:
  etl-networks:
    driver: bridge
